# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: 阿达的博客
email: billyang363@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://yangda75.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: yangda236246
github_username:  yangda75
host: 0.0.0.0
# comment:
disqus:
  shortname: bill363yang-github-com
# Build settings
markdown: kramdown
kramdown:
  input: GFM
  math_engine: mathjax
  syntax_highlighter: rouge
theme: minima
plugins:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
minima:
  skin: classic
author:
  name: yangda
  email: billyang363@gmail.com
google_analytics: UA-NNNNNNNN-N
#highlighter: rouge
