title: yda的博客
description: 不定时更新
author:
  name: yangda
  email: billyang363@gmail.com

theme: minima

twitter_username: yangda236246
github_username:  yangda75

repository: yangda75/yangda75.github.io

# comment:
disqus:
  shortname: bill363yang-github-com

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  math_engine: mathjax
  syntax_highlighter: rouge


exclude:
  - Gemfile
  - Gemfile.lock
minima:
  date_format: "%Y-%m-%d"
  
google_analytics: UA-NNNNNNNN-N
#highlighter: rouge
